name: Scheduled Fork Sync

on:
  schedule:
    - cron: '0 0 * * *' # This runs every single day at midnight (UTC)
  workflow_dispatch:   # This adds a manual "Run now" button just in case

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync Fork
        run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
